# Generated by Django 3.1.1 on 2020-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
