# Generated by Django 3.1.1 on 2020-09-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200917_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='stock',
        ),
    ]
