# Generated by Django 3.1.1 on 2020-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_items_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='text',
            field=models.CharField(default='Tiny room', max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
