# Generated by Django 3.1.1 on 2021-02-06 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_items_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость в долларах', max_digits=6, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(help_text='Наименование товара', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='items',
            name='text',
            field=models.CharField(help_text='Описание товара на 255 символов', max_length=255, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Комментарий на 255 символов', max_length=255, verbose_name='Комментарий')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
