# Generated by Django 3.1.1 on 2021-02-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='link',
            field=models.CharField(default='https://instagram.fgme1-1.fna.fbcdn.net/v/t51.2885-15/e35/91964292_577982559735852_343623272175491151_n.jpg?_nc_ht=instagram.fgme1-1.fna.fbcdn.net&_nc_cat=100&_nc_ohc=YpXUswrAfikAX9WClV2&tp=1&oh=72638d6a1e24d15ca974729fdef6dfe2&oe=604EB6C6', help_text='URL адрес', max_length=255, verbose_name='Ссылка на картинку'),
            preserve_default=False,
        ),
    ]
