# Generated by Django 3.1.1 on 2021-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_items_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='item_id',
        ),
        migrations.AddField(
            model_name='items',
            name='comment',
            field=models.ManyToManyField(to='App.Comments'),
        ),
    ]
