# Generated by Django 3.1.1 on 2021-02-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210211_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='comment',
        ),
        migrations.AddField(
            model_name='items',
            name='comment',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='App.comments'),
            preserve_default=False,
        ),
    ]
